all: locale/de/LC_MESSAGES/txtr_uploader.mo messages.pot

./tmp/uploader.glade.h: ../src/txtr/gui/uploader.glade
	intltool-extract --type=gettext/glade -l $^

messages.pot: ../src/txtr/gui/uploader.py ./tmp/uploader.glade.h
	xgettext  -k_ -kN_ --output messages.pot --from-code utf-8 $^

locale/de/LC_MESSAGES/txtr_uploader.mo: de.po
	msgfmt de.po -o locale/de/LC_MESSAGES/txtr_uploader.mo
